controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

locataires:
    path: /locataires
    methods: ["GET"]
    controller: App\Controller\LocatairesController::index

show_locataires:
    path: /modif-locataires/{id}
    methods: ["GET"]
    controller: App\Controller\LocatairesController::showLocataires

ajout_locataires:
    path: /ajouter-locataires
    methods: ["GET"]
    controller: App\Controller\LocatairesController::ajout

