controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_verify_email:
    path: /verify/email
    methods: ["GET"]
    controller: App\Controller\LocatairesController::verifyUserEmail

ajout_une_location:
    path: /ajout-une-location
    methods: ["GET", "POST"]
    controller: App\Controller\LocatairesController::ajoutUneLocation

location:
    path: /location
    methods: ["GET"]
    controller: App\Controller\LocationController::index